stages:
  - build
  - test-generate

build:
  stage: build
  tags:
    - online-build-small
  script:
    - mvn clean install

test-generate:
  stage: test-generate
  tags:
    - online-build-small
  script:
    - mvn archetype:generate
        -DarchetypeGroupId=com.microservice
        -DarchetypeArtifactId=archetype--microservice
        -DarchetypeVersion=0.0.1-SNAPSHOT
        -DgroupId=com.example
        -DartifactId=test-svc
        -Dpackage=com.example
        -DinteractiveMode=false
    - cd test-svc && mvn test
