#!/usr/bin/env bash
# Simulates Backstage fetch:template action locally
# Usage: ./test-skeleton.sh [groupId] [artifactId] [javaVersion]
set -e

GROUP_ID="${1:-com.example}"
ARTIFACT_ID="${2:-my-test-service}"
JAVA_VERSION="${3:-21}"
VERSION="0.0.1-SNAPSHOT"

PACKAGE_NAME="$(echo "$ARTIFACT_ID" | tr -d -- '-_' | tr '[:upper:]' '[:lower:]')"
PACKAGE_PATH="$(echo "$GROUP_ID" | tr '.' '/')/$PACKAGE_NAME"

OUT_DIR="/tmp/backstage-test/$ARTIFACT_ID"

echo "=== Backstage skeleton simulation ==="
echo "  groupId     : $GROUP_ID"
echo "  artifactId  : $ARTIFACT_ID"
echo "  packageName : $PACKAGE_NAME"
echo "  packagePath : $PACKAGE_PATH"
echo "  output      : $OUT_DIR"
echo ""

rm -rf "$OUT_DIR"
mkdir -p "$(dirname "$OUT_DIR")"
cp -r skeleton "$OUT_DIR"

# Rename placeholder directory to real package path
PLACEHOLDER_DIR="$OUT_DIR/src/main/java/\${{ values.packagePath }}"
REAL_DIR="$OUT_DIR/src/main/java/$PACKAGE_PATH"
mkdir -p "$(dirname "$REAL_DIR")"
mv "$PLACEHOLDER_DIR" "$REAL_DIR"

PLACEHOLDER_TEST_DIR="$OUT_DIR/src/test/java/\${{ values.packagePath }}"
REAL_TEST_DIR="$OUT_DIR/src/test/java/$PACKAGE_PATH"
mkdir -p "$(dirname "$REAL_TEST_DIR")"
mv "$PLACEHOLDER_TEST_DIR" "$REAL_TEST_DIR"

# Substitute template variables in all text files
find "$OUT_DIR" -type f \( -name "*.java" -o -name "*.xml" -o -name "*.yaml" -o -name "*.yml" -o -name "*.md" \) | while read -r f; do
  sed -i '' \
    -e "s|{{ values.groupId }}|$GROUP_ID|g" \
    -e "s|{{ values.artifactId }}|$ARTIFACT_ID|g" \
    -e "s|{{ values.packageName }}|$PACKAGE_NAME|g" \
    -e "s|{{ values.packagePath }}|$PACKAGE_PATH|g" \
    -e "s|{{ values.version }}|$VERSION|g" \
    -e "s|{{ values.javaVersion }}|$JAVA_VERSION|g" \
    -e "s|{{ values.description }}|Test service generated by simulation|g" \
    -e "s|{{ values.squad }}|platform|g" \
    -e "s|{{ values.owner }}|group:platform-team|g" \
    -e "s|{{ values.projectSlug }}|example/my-test-service|g" \
    -e "s|{{ values.gitRepoSsh }}|git@gitlab.com:example/my-test-service.git|g" \
    "$f"
done

echo "Checking for unresolved template variables..."
UNRESOLVED=$(grep -r '{{ values\.' "$OUT_DIR" --include="*.java" --include="*.xml" --include="*.yaml" --include="*.yml" 2>/dev/null || true)
if [ -n "$UNRESOLVED" ]; then
  echo "ERROR: Unresolved variables found:"
  echo "$UNRESOLVED"
  exit 1
else
  echo "  OK — no unresolved variables"
fi

echo ""
echo "Verifying package structure..."
MAIN_PKG="$OUT_DIR/src/main/java/$(echo "$GROUP_ID" | tr '.' '/')/$PACKAGE_NAME"
TEST_PKG="$OUT_DIR/src/test/java/$(echo "$GROUP_ID" | tr '.' '/')/$PACKAGE_NAME"
[ -d "$MAIN_PKG" ] && echo "  OK — main package: $MAIN_PKG" || { echo "  ERROR: main package not found"; exit 1; }
[ -d "$TEST_PKG" ] && echo "  OK — test package: $TEST_PKG" || { echo "  ERROR: test package not found"; exit 1; }

echo ""
echo "Running mvn test..."
cd "$OUT_DIR"
mvn test -q 2>&1
echo ""
echo "=== Simulation complete ==="
