apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.artifactId }}
  description: {{ values.description }}
  annotations:
    gitlab.com/project-slug: {{ values.projectSlug }}
  tags:
    - java
    - spring-boot
    - hexagonal
spec:
  type: service
  lifecycle: experimental
  owner: {{ values.owner }}
